[app]
name = "demo"
host = "0.0.0.0"
port = "8050"
key  = "this is your app key"

[mysql]
host = "49.234.114.127"
port = "5438"
username = "go_course"
password = "7MCx@RPh0NfkQD53"
database = "go_course"

[log]
level = "debug"
path = "logs"
format = "text"
to = "stdout"